AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Creating Inspector Assessment And Schedule
Parameters:
  ResourceGroupTagKey:
    Type: String
    Default: "Inspector"
    Description: Input Tag Key
  ResourceGroupTagValue:
    Type: String
    Default: "true"
    Description: Input Tag Value

Resources:
  MyInspectoryResourceGroup:
    Type: AWS::Inspector::ResourceGroup
    Properties:
      ResourceGroupTags:
        - Key: !Ref ResourceGroupTagKey
          Value: !Ref ResourceGroupTagValue

  MyInspectorTarget:
    Type: AWS::Inspector::AssessmentTarget
    Properties:
      ResourceGroupArn: !Ref MyInspectoryResourceGroup

  MyInspectorTemplate:
    Type: AWS::Inspector::AssessmentTemplate
    Properties:
      AssessmentTargetArn: !Ref MyInspectorTarget
      DurationInSeconds: 3600
      RulesPackageArns:
        # Common Vulnerabilities and Exposures
        - arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-gHP9oWNT
        # CIS Operating System Security Configuration Benchmarks
        - arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-7WNjqgGu
        # Security Best Practices
        # - arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-bBUQnxMq
        # Runtime Behavior Analysis
        # - arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-knGBhqEu

  EventsInvokeInspectorAssessmentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "EventsInvokeInspectorAssessmentRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies: 
        - 
          PolicyName: "AllowInspectorAssessment"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action:
                  - "inspector:StartAssessmentRun"
                Resource: "*"
      Path: "/service-role/"

  MyInspectorEventsWeekly:
    Type: AWS::Events::Rule
    Properties: 
      Description: "Scheduled Inspector Assessment"
      ScheduleExpression: "rate(7 days)"
      State: "ENABLED"
      Targets:
        - Arn: !Ref MyInspectorTemplate
          Id: "TargetInspectorTemplate"
          RoleArn: !GetAtt EventsInvokeInspectorAssessmentRole.Arn
          
Outputs:
  MyInspectorTemplateArn:
    Description: Information MyInspectorTemplate Arn
    Value: !Ref MyInspectorTemplate
